// This file is generated and will be overwritten automatically.

#import <Foundation/Foundation.h>

@class MBNNFixLocation;
@class MBNNStep;

NS_SWIFT_NAME(UserFeedbackMetadata)
__attribute__((visibility ("default")))
@interface MBNNUserFeedbackMetadata : NSObject

// This class provides custom init which should be called
- (nonnull instancetype)init NS_UNAVAILABLE;

// This class provides custom init which should be called
+ (nonnull instancetype)new NS_UNAVAILABLE;

- (nonnull instancetype)initWithFeedbackId:(nonnull NSString *)feedbackId
                           locationsBefore:(nonnull NSArray<MBNNFixLocation *> *)locationsBefore
                            locationsAfter:(nonnull NSArray<MBNNFixLocation *> *)locationsAfter
                                      step:(nullable MBNNStep *)step;

/** UUID of the feedback must be generated by the caller and provided to metadata */
@property (nonatomic, readonly, nonnull, copy) NSString *feedbackId;

@property (nonatomic, readonly, nonnull, copy) NSArray<MBNNFixLocation *> *locationsBefore;
@property (nonatomic, readonly, nonnull, copy) NSArray<MBNNFixLocation *> *locationsAfter;
@property (nonatomic, readonly, nullable) MBNNStep *step;

@end
